### ISSUE TITLE
Option for working with fat32 partitions less than 512 MiB

### ISSUE THREAD

**Issue by ptrNine** [ya-mouse/fatresize#11]
It would be great, if fatresize had a special option for working with fat32 partitions less than 512 MiB. 

Mostly many EFI partitions has size less than 512 MiB and fatresize can't work properly with them.

The most incomprehensible thing is why "fatresize -i" show "Min size" also limited to 512 MiB.

**Comment by ya-mouse** [comment]
Will be fixed in 1.1.0. Thanks for reporting.
