### ISSUE TITLE
"Killed" with no verbosity

### ISSUE THREAD

**Issue by jsit** [ya-mouse/fatresize#12]
Attempted on an external WD:

```
~ $ sudo fatresize -p -v -s 1800G /dev/sdb2
fatresize 1.0.2 (06/16/18)
.Resizing file system.
Killed
```

**Comment by ya-mouse** [comment]
Would you mind to paste last logs from dmesg?
Also in the separate terminal try to run:
```
watch -n 1 free -h
```
To check how the memory is consumed during resize process.

**Comment by ya-mouse** [comment]
No activitity. Re-open if any.
