### ISSUE TITLE
FAT12 support

### ISSUE THREAD

**Issue by mikebdp2** [ya-mouse/fatresize#14]
I need to resize a floppy image from 1440KB _(1474560 bytes)_ "High Density" aka standard floppy to 2880KB _(2949120 bytes)_ "Extended Density" floppy, and sadly discovered there are no opensource Linux tools for that! Manual hexedit of 0x13/0x14 bytes from 0x0B40 to 0x1680 and 0x18 byte from 0x12 to 0x24 - also didn't work for me _(but I just learned about FAT structure and may be missing something)_. + #15 

Please add FAT12 resizing support - it may be really important in some situations.

**Comment by ya-mouse** [comment]
Unfortunetally, FAT12 is not suppoted by Parted:

https://git.savannah.gnu.org/gitweb/?p=parted.git;a=blob;f=libparted/fs/fat/bootsector.c;h=0c3ae77d391140934efe20903e5f5a4369a17c16;hb=8c50fec522f475c51e2aaa3c972ce4c6690dda92#l215

You may try to raise the feature request in Parted project instead.
