### ISSUE TITLE
Strange error for loop devices like /dev/loop0: "You must specify exactly one existing device."

### ISSUE THREAD

**Issue by mikebdp2** [ya-mouse/fatresize#15]
As I don't have a physical device for my floppy image (see #14), I've created a /dev/loop0 device with a command
```
sudo losetup /dev/loop1 ./floppy.img
```
However, when I try to use a command like
```
sudo fatresize -s 2880k /dev/loop1
```
I get this output:
```
fatresize 1.0.3 (03/05/20)
You must specify exactly one existing device.
```
Perhaps this has to do with /dev/loop1 device having one more letter than i.e. /dev/sdd1

**Comment by ya-mouse** [comment]
I'm going to add a logic to handle loop-devices as well. Thank you for reporting.

**Comment by Xses-1** [comment]
I still have this error.

```
# fatresize -s 256M /dev/loop1
fatresize 1.1.0 (20201114)
You must specify exactly one existing device.
```
