### ISSUE TITLE
Cannot resize FAT partitions on SD cards (like e.g. /dev/mmcblk0p1)

### ISSUE THREAD

**Issue by sriemer** [ya-mouse/fatresize#2]
Hi,

I'm the current SUSE parted maintainer and it has been reported to me that calling `fatresize` with `/dev/mmcblk0p1` fails (openSUSE bug: https://bugzilla.suse.com/show_bug.cgi?id=959181).

I can reproduce this with latest master commit 46cf019fe771.

```
# ./fatresize -s 5G /dev/mmcblk0p1
fatresize 1.0.3 ()
Error: Could not stat device /dev/mmcblk0p - No such file or directory.
```

Parted supports those devices properly. Can you please develop a fix? TIA

**Comment by sriemer** [comment]
Looks like I have to fix this myself as soon as I get rid of higher priority bugs.

**Comment by memarko** [comment]
it works if you create symbolic link without number at the end

**Comment by sriemer** [comment]
I know. As a package maintainer I need a fix - not a workaround.
